spring.application.name=api-booke

server.port=8081

# Dados para configurar conexão com BD postgresql

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5437/booke
spring.datasource.username=user_adm
spring.datasource.password=useradm

spring.jpa.properties.hibernate.default_schema=booke

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mostra também os valores dos parâmetros
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Mostra SQL em inserts/updates/deletes
logging.level.org.hibernate.SQL=DEBUG


